stages:
  - test
  - stats
  - release

lint:
  stage: test
  tags:
    - openjdk-8
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gradle-ktlint

unittest:
  stage: test
  tags:
    - openjdk-8
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gradle-jacoco papio-cli
    - gradle-jacoco papio-lib

gitstats:
  stage: stats
  tags:
    - python3
    - gitstats
    - progstats
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gitstats-gen

docgen:
  stage: stats
  tags:
    - openjdk-8
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gradle-dokka papio-cli
    - gradle-dokka papio-lib

build_jar:
  stage: test
  only:
    - master
    - develop
  tags:
    - openjdk-8
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - gradle-build-jar papio-lib
    - gradle-build-jar papio-cli
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/

release_upload:
  stage: release
  only:
    - master
  tags:
    - python3
  script:
    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"
