stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/papio.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/papio.git develop -f

unittest:
  stage: test
  tags:
    - gradle
  script:
    - gradle test jacocoTestReport
    - rsync -av --delete-after papio-lib/build/reports/coverage/ /var/www/coverage.namibsun.net/public_html/papio-lib

lint:
  stage: test
  tags:
    - gradle
  script:
    - gradle ktlint -q